apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacityp4backend
  labels:
    app: udacityp4backend
spec:
  selector:
    matchLabels:
        app: udacityp4backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacityp4backend
    spec:
      containers:
        - name: udacityp4backend
          image: 746263314120.dkr.ecr.us-east-1.amazonaws.com/udacityp4backend:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
